name: Build Desktop App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo'yu Çek
      uses: actions/checkout@v3

    - name: Node.js Kur (v20)
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: NW.js Builder CLI Kur ve Derle
      run: |
        npm install nw-builder -g
        nwbuild --mode=build --version=latest --flavor=sdk --platforms=win64 --outDir=dist ./package.json

    - name: Release Oluştur ve .exe Yükle
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}