name: Build Desktop App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo'yu Cek
      uses: actions/checkout@v3

    - name: Node.js Kur
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: NW.js Builder CLI Kur ve Derle
      run: |
        npm install nw-builder -g
        nwbuild --platforms win64 --outDir dist .

    - name: Release Oluştur ve .exe Yükle
      uses: softprops/action-gh-release@v1
      with:
        files: dist/EXIF-B-Gone/win64/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}